name: 📄 Fill Names & Descriptions

on:
  workflow_dispatch:

jobs:
  fill_names:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v3

      - name: 🛠 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📥 Install Dependencies
        run: npm install axios dotenv @supabase/supabase-js

      - name: 📄 Fülle Namen & Beschreibungen aus Google
        run: node scripts/fill_names_and_descriptions.js
